= Reference

. https://gist.github.com/jmprusi/8e7369376e42ffe1cd5278e919b50cd4#file-istio-adapter-md

. https://docs.google.com/presentation/d/1PaE3RqyKoadllKHlPg0-kHcUrTuCeIdAe81CMk12iWw/
+
3scale Next.Gen and Istio
. https://docs.google.com/document/d/1ymRd8rxvECr3TUqlNVAExDrIkp-XAxo25yt2jvhd18I/edit
+
OpenTracing for APIcast (productized in next release of 3scale)
. https://gist.github.com/jmprusi/eb7a62df02756db94072cab4d8ca645e
+
How to deploy APIcast inside the service mesh
+
APIcast gets full mTLS that can be viwed in the itio observability tools
+
Will also respect destination rules defined by istio
. https://github.com/3scale/istio-integration/tree/master/3scaleAdapter
+
PoC Around gRPC Istio Mixer adapter for 3scale
+
This is project lacks some documentation, I will work on that soon, but basically allows to use 3scale as a decision engine inside Istio, without using APIcast.

. https://docs.google.com/presentation/d/10wHKTU09DDpw5_kCdL3XM7Kt6WkuMvCAcDWkDk10yxg/edit
+
Intro to Cloud-Native App Dev

. https://github.com/opentracing-contrib/nginx-opentracing
+
nginx-opentracing

== Datawire Ambassador
. https://www.getambassador.io/about/why-ambassador/

== Apigee Mixer in Istio

. https://groups.google.com/forum/#!topic/istio-users/zKtk4uswGLQ
+
-----
We absolutely want Istio to be able to play in this space, both as a standalone project and as the datapath for existing commercial API management solutions.

Istio can already validate JWTs and enforce basic rate limiting.  See docs here and here.

Those are fine for some use cases (not many unique clients), but you may want to have a system that isn't dependent on CRDs for clients or individual rate limits. 
To show that, we've released a Mixer adapter that is an integration with our Apigee Edge enterprise API management product. 
This allows you to use Apigee for, for example, creation of API keys or client IDs (Apigee has a portal in which your customers can create their own credentials self-service) and rate limits. 
Istio can then enforce the policies defined in the api management system by way of a Mixer adapter.
-----

== Guidance from Mark Cheshire

. Red Hat will be at the forefront of integrating Istio into the container platfrom (OpenShift) as well as with API Management (3scale)

. 3scale has always had the same architectural approach as Istio - to separate the control plane from the data plane - which will lead to better integration.

. Competitors without the separation of gateway and management server or who are focused primarily on the gateway will likely not coexist well

. Istio is primarily focused on advanced traffic management

. 3scale is primarily focused the end-to-end experience of how to open, control, and manage APIs (including Microservices) - authorization, access policies, developer management, developer portal and docs

. The main overlapping area right now is analytics - 3scale is focused more on the app managers and API architectures, while Istio is focused more on developers and dev ops

. In future there will be more overlapping areas, and we will see a similar bifurcation of views. Different companies will have different preferences.

. Bottom line we aim to be the best company at integrating traditional API Management with Service Mesh environments though a whole-hearted embrace of Istio.
